apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-v1.0
spec:
  replicas: 2
  selector:
    app: santander-phpinfo
  template:
    metadata:
      labels:
        app: santander-phpinfo
    spec:
      containers:
        - name: php
          image: index.docker.io/ismaldk/santander-phpinfo:1.0
          ports:
            - containerPort: 8080
